export const SUCCESS_INIT_LIST_USERS = 'SUCCESS_INIT_LIST_USERS'
export const SUCCESS_INIT_EDIT_USER = 'SUCCESS_INIT_EDIT_USER'
export const SUCCESS_UPDATE_USER = 'SUCCESS_UPDATE_USER'

export const FAILURE_GET_USERS = 'FAILURE_GET_USERS'
export const SUCCESS_ADD_USER = 'SUCCESS_ADD_USER'
export const SUCCESS_DELETE_USER = 'SUCCESS_DELETE_USER'

export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED'
export const SUCCESS_ACCOUNT_REGISTER = 'SUCCESS_ACCOUNT_REGISTER'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
